dist: trusty
sudo: false
language: node_js
node_js:
  - 6
cache: yarn
script:
  - yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: hi@qwp6t.me
  api_key:
    secure: yJw8TFdk7kU+3VDy3e3uOBMcHZB6OQwdxPhyMtNc2d4OUMd6pTn3e7TcRmvXU6boa4vWmjenL3mvAKpxFxZA1jTjSGWJZIBIRQNttZKUQjAbwcDtu82nl91K2i3aIfDiF49mntNlpRHJDPF7dXmSJav7aB2R2Ykiffbq27V+keMKp2PRqqE7e/0OvyooMoaBz4or6IyxwWiJPMcnAE1F0p85/JLont6FQ9q9OJMwNjkPi3fFWb0BP5LJ2OwS6jGqDBm9sEJ8T+OVJoea58C4bFHdKeV7qhm+E5wtFrXhlpHpzOaAygPzQ98PdXia7aCUWj4pO0TdLw7zXFAKk3LZ9b2Cq5Aw7bwv+P2GYxVnyFqIlDbrLUHJCfu2QxsOZXMmXghAbgKS5Q90wfsLM/XJQwCYioTN9cXLz7mJjdF2H4aCqJE2xJNVfOgh9mn6J4FkcEzQqA2n0PLyglBzW4mAfd+1vNJmr9YXPf2MSXuej4FQHkCrukkxVjQQf+GlFWclqfNYEQZW45pXh4LoKRjC3h/MFAISBF2kUkferNgcyub0Qp/Dp7PHrrGxf3kkA4swkaZOvume2pLy6RAiQer1AlZH43rDw3fF7CAfyw/6aREjCFIbxqI/7vz2nIQrtSU2Lu53K+LdbGyDa0v3hWKRLTwxkqn74oZ15uTPgc51O+0=
  on:
    tags: true
notifications:
  email:
    on_success: always
